name: Build docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      BUILD_TAG:
        required: true
        description: 'enter build tag'
        default: "1.00"
        type: string

env:
  AWS_REGION: us-east-1  # Region-wide setting

permissions:
  id-token: write
  contents: read

jobs:
  Build_docker_image:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Set and build Docker image with tag
        run: |
          $buildTag = "${{ github.event.inputs.BUILD_TAG }}"
          echo "Using Docker tag: $buildTag"
          docker build -t testapp:$buildTag .
