name: Build docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      BUILD_TAG:
        required: true
        description: 'Enter build tag'
        default: "1.00"
        type: string

env:
  AWS_REGION: us-east-1
  BUILD_TAG: ${{ github.event.inputs.BUILD_TAG || 'latest' }}

permissions:
  id-token: write
  contents: read

jobs:
  Build_docker_image:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          Write-Host "Using Docker tag: $env:BUILD_TAG"
          docker build -t testapp:$env:BUILD_TAG .