name: Build docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      BUILD_TAG:
        required: true
        description: 'enter build tag'
        default: "1.00"
        type: string

env:
  AWS_REGION: us-east-1  # Change to reflect your Region

permissions:
  id-token: write   # Required for requesting the JWT
  contents: read    # Required for actions/checkout

jobs:
  Build_docker_image:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell  # Set shell to PowerShell

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Set IMAGE_TAG environment variable
        run: |
          $buildTag = "${{ github.event.inputs.BUILD_TAG }}"
          echo "IMAGE_TAG=$buildTag" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Host "Docker image tag will be: $buildTag"

      - name: Build Docker image
        run: |
          docker build -t testapp:$env:IMAGE_TAG .
